const { createClient } = supabase;
const sb = createClient(DISPONIBLE_CONFIG.supabaseUrl, DISPONIBLE_CONFIG.supabaseKey);
const root = document.querySelector('#admin-app');
let session = null, section = 'dashboard', query = '', filters = {};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const toast=m=>{const x=document.createElement('div');x.className='toast';x.textContent=m;document.body.append(x);setTimeout(()=>x.remove(),2800)};
const labels={dashboard:'Dashboard',users:'Usuarios',workers:'Trabajadores',businesses:'Negocios',reports:'Reportes',reviews:'Reseñas',boosts:'Boosts',payments:'Pagos',geography:'Geografía',catalog:'Categorías y skills',settings:'Configuración'};
const icons={dashboard:'▦',users:'♙',workers:'◉',businesses:'▣',reports:'⚑',reviews:'★',boosts:'↗',payments:'¤',geography:'⌖',catalog:'◇',settings:'⚙'};
function nav(){return Object.keys(labels).map(k=>`<button class="nav-item ${section===k?'active':''}" onclick="go('${k}')"><span>${icons[k]}</span>${labels[k]}</button>`).join('')}
async function init(){const r=await sb.auth.getSession();session=r.data.session;sb.auth.onAuthStateChange((_e,s)=>{session=s;render()});render()}
async function adminCheck(){if(!session)return false;const {data,error}=await sb.from('users').select('id,role,status,email').eq('id',session.user.id).maybeSingle();return !error&&data?.role==='admin'&&data?.status==='active'}
async function render(){if(!(await adminCheck())) return renderLogin(); root.innerHTML=`<div class="admin-shell"><aside class="admin-sidebar"><div class="admin-brand"><div class="brand-mark">D</div><div><strong>DISPONIBLE</strong><small>Administración</small></div></div><nav>${nav()}</nav><div class="sidebar-foot"><span>● Sistema protegido</span><button class="logout-link" onclick="logout()">Cerrar sesión</button></div></aside><main class="admin-main"><header class="admin-header"><button class="mobile-menu" onclick="document.body.classList.toggle('sidebar-open')">☰</button><div><div class="eyebrow">PANEL DE CONTROL</div><h1>${labels[section]}</h1></div><div class="admin-user"><span class="status-dot"></span><span>Administrador</span></div></header><section id="admin-content" class="admin-content"></section></main></div>`;await loadSection()}
function renderLogin(){root.innerHTML=`<main class="admin-login"><div class="login-box"><div class="brand-mark large">D</div><div class="eyebrow">DISPONIBLE</div><h1>Panel de administración</h1><p class="muted">Acceso exclusivo para administradores autorizados.</p><form onsubmit="event.preventDefault();login()"><label>Email<input id="email" type="email" autocomplete="username" required></label><label>Contraseña<input id="pass" type="password" autocomplete="current-password" required></label><button class="primary full" type="submit">Ingresar al panel</button></form><p class="login-note">La autorización se valida en Supabase. El frontend nunca asigna permisos de administrador.</p></div></main>`}
function go(x){section=x;query='';filters={};document.body.classList.remove('sidebar-open');render()}
function pageHead(title,desc,actions=''){return `<div class="page-head"><div><h2>${title}</h2><p class="muted">${desc}</p></div><div class="page-actions">${actions}</div></div>`}
function searchBar(placeholder='Buscar...'){return `<div class="toolbar"><div class="search"><span>⌕</span><input value="${esc(query)}" placeholder="${placeholder}" oninput="query=this.value;filterRows()"></div><button class="filter-btn" onclick="toggleFilters()">⚲ Filtros</button></div><div id="filter-panel" class="filter-panel hidden"></div>`}
async function loadSection(){const c=document.querySelector('#admin-content');if(!c)return;c.innerHTML='<div class="loading-card">Cargando…</div>';try{if(section==='dashboard')return dashboard(c);if(section==='users')return entityList(c,'users',['email','role','status','created_at'],'Usuarios','Personas registradas en la plataforma.');if(section==='workers')return entityList(c,'worker_profiles',['first_name','last_name','profile_completion','rating_average','updated_at'],'Trabajadores','Perfiles de trabajadores y disponibilidad.');if(section==='businesses')return entityList(c,'business_profiles',['business_name','status','profile_completion','rating_average'],'Negocios','Perfiles de empresas y actividad.');if(section==='reports')return moderationList(c,'reports',['reason','status','created_at'],'Reportes','Denuncias pendientes de revisión.','report');if(section==='reviews')return moderationList(c,'reviews',['rating','status','created_at'],'Reseñas','Contenido de reputación para moderar.','review');if(section==='boosts')return moderationList(c,'boosts',['boost_type','status','starts_at','ends_at'],'Boosts','Promociones de visibilidad de trabajadores.','boost');if(section==='payments')return moderationList(c,'payments',['amount','status','created_at'],'Pagos','Registros de pagos y estados.','payment');if(section==='geography')return geography(c);if(section==='catalog')return catalog(c);if(section==='settings')return settings(c)}catch(e){c.innerHTML=`<div class="empty-card"><b>No se pudo cargar esta sección.</b><p>${esc(e.message)}</p></div>`}}
async function count(table,extra){let q=sb.from(table).select('*',{count:'exact',head:true});if(extra)q=extra(q);const r=await q;return r.count||0}
async function dashboard(c){const [users,workers,businesses,active,available,contacts,reports,featured,cities]=await Promise.all([count('users'),count('worker_profiles'),count('business_profiles'),count('users',q=>q.eq('status','active')),count('availability',q=>q.eq('is_active',true)),count('contacts'),count('reports',q=>q.eq('status','pending')),count('boosts',q=>q.eq('status','active')),count('cities',q=>q.eq('status','active'))]);c.innerHTML=pageHead('Centro de control','Resumen general de DISPONIBLE')+`<div class="metric-grid">${[['Usuarios',users,'Personas registradas'],['Trabajadores',workers,'Perfiles creados'],['Negocios',businesses,'Empresas registradas'],['Activos',active,'Cuentas activas'],['Disponibles ahora',available,'Disponibilidad activa'],['Contactos',contacts,'Contactos registrados'],['Reportes pendientes',reports,'Requieren revisión'],['Destacados',featured,'Boosts activos'],['Ciudades activas',cities,'Cobertura actual']].map(x=>`<article class="metric-card"><div class="metric-icon">${x[0][0]}</div><div><strong>${x[1]}</strong><span>${x[0]}</span><small>${x[2]}</small></div></article>`).join('')}</div><div class="dashboard-grid"><article class="panel"><h3>Acciones rápidas</h3><div class="quick-grid"><button onclick="go('users')">Gestionar usuarios</button><button onclick="go('workers')">Revisar trabajadores</button><button onclick="go('businesses')">Revisar negocios</button><button onclick="go('reports')">Moderar reportes</button><button onclick="go('geography')">Gestionar ciudades</button><button onclick="go('settings')">Configuración</button></div></article><article class="panel"><h3>Estado del sistema</h3><div class="system-row"><span>Base de datos</span><b class="ok">Operativa</b></div><div class="system-row"><span>Control de acceso</span><b class="ok">RLS activo</b></div><div class="system-row"><span>Administrador</span><b class="ok">Autorizado</b></div></article></div>`}
async function fetchRows(table,cols){let q=sb.from(table).select('id,'+cols.join(',')).limit(100);const r=await q;if(r.error)throw r.error;return r.data||[]}
async function entityList(c,table,cols,title,desc){c.innerHTML=pageHead(title,desc)+searchBar(table==='users'?'Buscar por email o estado...':'Buscar por nombre...')+`<div id="rows-area" class="table-card"><div class="loading-card">Cargando…</div></div>`;const rows=await fetchRows(table,cols);window._adminRows={table,rows,cols};renderRows();}
function renderRows(){const box=document.querySelector('#rows-area');if(!box)return;let rows=(window._adminRows?.rows||[]).filter(r=>JSON.stringify(r).toLowerCase().includes(query.toLowerCase()));const cols=window._adminRows.cols,table=window._adminRows.table;box.innerHTML=`<div class="table-wrap"><table><thead><tr><th>Identidad</th>${cols.map(x=>`<th>${pretty(x)}</th>`).join('')}<th>Acciones</th></tr></thead><tbody>${rows.length?rows.map(r=>`<tr><td><strong>${esc(r.email||r.business_name||[r.first_name,r.last_name].filter(Boolean).join(' ')||short(r.id))}</strong></td>${cols.map(x=>`<td>${cell(r[x],x)}</td>`).join('')}<td><button class="small-btn" onclick="openDetail('${table}','${r.id}')">Ver ficha</button></td></tr>`).join(''):`<tr><td colspan="${cols.length+2}" class="empty-cell">No hay resultados.</td></tr>`}</tbody></table></div>`}
function filterRows(){renderRows()}
function toggleFilters(){const p=document.querySelector('#filter-panel');if(!p)return;p.classList.toggle('hidden');p.innerHTML=`<div class="filter-grid"><label>Estado<select onchange="filters.status=this.value;applyFilter()"><option value="">Todos</option><option>active</option><option>paused</option><option>suspended</option><option>deleted</option><option>pending</option><option>published</option><option>hidden</option></select></label><label>Orden<select><option>Más recientes</option><option>Más antiguos</option></select></label></div>`}
function applyFilter(){if(window._adminRows){const s=filters.status;window._adminRows.rows=window._adminRows.rows.filter(r=>!s||r.status===s);renderRows()}}
function pretty(x){return {profile_completion:'Completitud',rating_average:'Valoración',created_at:'Registrado',updated_at:'Actualizado',status:'Estado',role:'Rol',email:'Email',boost_type:'Tipo',starts_at:'Inicio',ends_at:'Fin',amount:'Monto',rating:'Valoración',reason:'Motivo'}[x]||x.replaceAll('_',' ')}
function cell(v,k){if(v===null||v===undefined)return '—';if(k==='status')return `<span class="pill ${statusClass(v)}">${esc(v)}</span>`;if(k==='rating_average'||k==='rating')return `★ ${esc(v)}`;if(k==='profile_completion')return `<div class="progress"><i style="width:${Math.min(Number(v)||0,100)}%"></i></div><small>${esc(v)}%</small>`;if(k.includes('_at')||k==='created_at')return esc(new Date(v).toLocaleString('es-AR'));if(k==='amount')return `$ ${esc(v)}`;return esc(v)}
function statusClass(v){return ['active','published','approved'].includes(v)?'success':['pending','paused'].includes(v)?'warning':['suspended','blocked','rejected','hidden','deleted'].includes(v)?'danger':''}
function short(id){return String(id||'').slice(0,8)+'…'}
async function moderationList(c,table,cols,title,desc,type){c.innerHTML=pageHead(title,desc)+searchBar('Buscar por estado o contenido...')+`<div id="rows-area" class="table-card"><div class="loading-card">Cargando…</div></div>`;const rows=await fetchRows(table,cols);window._adminRows={table,rows,cols,type};renderModerationRows()}
function renderModerationRows(){const box=document.querySelector('#rows-area');if(!box)return;let rows=(window._adminRows.rows||[]).filter(r=>JSON.stringify(r).toLowerCase().includes(query.toLowerCase()));const cols=window._adminRows.cols,table=window._adminRows.table;box.innerHTML=`<div class="table-wrap"><table><thead><tr>${cols.map(x=>`<th>${pretty(x)}</th>`).join('')}<th>Acciones</th></tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${cols.map(x=>`<td>${cell(r[x],x)}</td>`).join('')}<td><button class="small-btn" onclick="openModeration('${table}','${r.id}')">Revisar</button></td></tr>`).join(''):`<tr><td colspan="${cols.length+1}" class="empty-cell">No hay registros.</td></tr>`}</tbody></table></div>`}
async function openModeration(table,id){const r=window._adminRows.rows.find(x=>x.id===id)||{};if(table==='reports')return openReportModeration(r);if(table==='reviews'){const [a,b]=await Promise.all([sb.from('users').select('email,role,status').eq('id',r.reviewer_user_id).maybeSingle(),sb.from('users').select('email,role,status').eq('id',r.reviewed_user_id).maybeSingle()]);const reviewer=a.data||{},reviewed=b.data||{};openModal(`<div class="modal-head"><div><span class="eyebrow">MODERACIÓN</span><h2>Revisar reseña</h2></div><button class="close" onclick="closeModal()">×</button></div><div class="detail-list"><div><span>Autor</span><b>${esc(reviewer.email||short(r.reviewer_user_id))}</b></div><div><span>Perfil evaluado</span><b>${esc(reviewed.email||short(r.reviewed_user_id))}</b></div><div><span>Valoración</span><b>★ ${esc(r.rating)}</b></div><div><span>Estado</span><b>${esc(r.status)}</b></div><div><span>Comentario</span><b>${esc(r.comment||'Sin comentario')}</b></div><div><span>Fecha</span><b>${esc(r.created_at?new Date(r.created_at).toLocaleString('es-AR'):'—')}</b></div></div><div class="modal-actions"><button class="secondary" onclick="setRecordStatus('reviews','${id}','hidden')">Ocultar</button><button class="danger-btn" onclick="setRecordStatus('reviews','${id}','rejected')">Rechazar</button><button class="primary" onclick="setRecordStatus('reviews','${id}','published')">Publicar</button></div>`);return}openModal(`<div class="modal-head"><div><span class="eyebrow">MODERACIÓN</span><h2>Revisar registro</h2></div><button class="close" onclick="closeModal()">×</button></div><div class="detail-list">${Object.entries(r).map(([k,v])=>`<div><span>${pretty(k)}</span><b>${esc(typeof v==='object'?JSON.stringify(v):v)}</b></div>`).join('')}</div><div class="modal-actions"><button class="secondary" onclick="closeModal()">Cerrar</button></div>`)}
function openReportModeration(r){openModal(`<div class="modal-head"><div><span class="eyebrow">REPORTE</span><h2>Moderar denuncia</h2></div><button class="close" onclick="closeModal()">×</button></div><div class="detail-list">${Object.entries(r).map(([k,v])=>`<div><span>${pretty(k)}</span><b>${esc(typeof v==='object'?JSON.stringify(v):v)}</b></div>`).join('')}</div><label>Notas del administrador<textarea id="report-notes" rows="5" maxlength="1000" placeholder="Qué se revisó y qué decisión se tomó…"></textarea></label><div class="modal-actions"><button class="secondary" onclick="saveReportDecision('${r.id}','reviewing')">Marcar en revisión</button><button class="danger-btn" onclick="saveReportDecision('${r.id}','rejected')">Rechazar</button><button class="primary" onclick="saveReportDecision('${r.id}','resolved')">Resolver</button></div>`)}
async function saveReportDecision(id,status){const notes=document.querySelector('#report-notes')?.value.trim()||null;const payload={status,admin_notes:notes};if(status==='resolved'||status==='rejected')Object.assign(payload,{resolved_at:new Date().toISOString(),resolved_by:session.user.id});else Object.assign(payload,{resolved_at:null,resolved_by:null});const {error}=await sb.from('reports').update(payload).eq('id',id);if(error)return toast(error.message);toast('Reporte actualizado');closeModal();loadSection()}
async function setRecordStatus(table,id,status){const {error}=await sb.from(table).update({status}).eq('id',id);if(error)return toast(error.message);toast('Estado actualizado');closeModal();loadSection()}

async function openDetail(table,id){
  if(table==='boosts')return openBoostDetail(id);
  if(table==='payments')return openPaymentDetail(id);
  const {data,error}=await sb.from(table).select('*').eq('id',id).maybeSingle();
  if(error)return toast(error.message);
  const canStatus=['users','business_profiles','reviews','reports'].includes(table);
  openModal(`<div class="modal-head"><div><span class="eyebrow">FICHA</span><h2>${esc(data?.business_name||data?.email||[data?.first_name,data?.last_name].filter(Boolean).join(' ')||'Perfil')}</h2></div><button class="close" onclick="closeModal()">×</button></div><div class="detail-list">${Object.entries(data||{}).map(([k,v])=>`<div><span>${pretty(k)}</span><b>${esc(typeof v==='object'?JSON.stringify(v):v)}</b></div>`).join('')}</div><div class="modal-actions">${canStatus?`<button class="secondary" onclick="promptStatus('${table}','${id}')">Cambiar estado</button>`:''}<button class="danger-btn" onclick="closeModal()">Cerrar</button></div>`)
}
async function openBoostDetail(id){
  const {data:b,error}=await sb.from('boosts').select('*').eq('id',id).maybeSingle();
  if(error||!b)return toast(error?.message||'Boost no encontrado.');
  const {data:w}=await sb.from('worker_profiles').select('id,user_id,first_name,last_name,profile_completion,rating_average').eq('id',b.worker_id).maybeSingle();
  const name=[w?.first_name,w?.last_name].filter(Boolean).join(' ')||b.worker_id;
  openModal(`<div class="modal-head"><div><span class="eyebrow">BOOST</span><h2>${esc(name)}</h2></div><button class="close" onclick="closeModal()">×</button></div><div class="detail-list"><div><span>Tipo</span><b>${esc(b.boost_type)}</b></div><div><span>Estado</span><b>${esc(b.status)}</b></div><div><span>Inicio</span><b>${esc(b.starts_at)}</b></div><div><span>Fin</span><b>${esc(b.ends_at)}</b></div><div><span>Perfil</span><b>${esc(w?.profile_completion??'—')}% completado · ★ ${esc(w?.rating_average??0)}</b></div></div><p class="muted">El boost no garantiza contratación. Su activación solo aumenta levemente la visibilidad y siempre respeta el ranking de relevancia.</p><div class="modal-actions"><button class="secondary" onclick="promptStatus('boosts','${id}')">Cambiar estado</button><button class="danger-btn" onclick="closeModal()">Cerrar</button></div>`)
}
async function openPaymentDetail(id){
  const {data:p,error}=await sb.from('payments').select('*').eq('id',id).maybeSingle();
  if(error||!p)return toast(error?.message||'Pago no encontrado.');
  const {data:u}=await sb.from('users').select('email,role,status').eq('id',p.user_id).maybeSingle();
  openModal(`<div class="modal-head"><div><span class="eyebrow">PAGO</span><h2>${esc(u?.email||p.user_id)}</h2></div><button class="close" onclick="closeModal()">×</button></div><div class="detail-list"><div><span>Tipo</span><b>${esc(p.type)}</b></div><div><span>Monto</span><b>${esc(p.amount)} ${esc(p.currency)}</b></div><div><span>Estado</span><b>${esc(p.status)}</b></div><div><span>Proveedor</span><b>${esc(p.provider||'—')}</b></div><div><span>Referencia</span><b>${esc(p.provider_reference||'—')}</b></div><div><span>Usuario</span><b>${esc(u?.role||'—')} · ${esc(u?.status||'—')}</b></div><div><span>Creado</span><b>${esc(p.created_at)}</b></div></div><p class="muted">Los pagos se registran como pendientes hasta que el sistema de pago o el administrador autorizado confirme el estado. El usuario no puede autoaprobarse un pago.</p><div class="modal-actions"><button class="secondary" onclick="promptStatus('payments','${id}')">Cambiar estado</button><button class="danger-btn" onclick="closeModal()">Cerrar</button></div>`)
}

async function promptStatus(table,id){const allowed={users:['active','paused','suspended','deleted'],business_profiles:['active','paused','suspended','deleted'],reviews:['pending','published','hidden','rejected'],reports:['pending','reviewing','resolved','rejected'],boosts:['pending','active','expired','cancelled'],payments:['pending','paid','failed','refunded','cancelled']}[table];if(!allowed)return toast('Esta sección no admite cambio de estado desde aquí.');const status=prompt(`Estado nuevo: ${allowed.join(', ')}`);if(!status||!allowed.includes(status))return toast('Estado no válido.');const {error}=await sb.from(table).update({status}).eq('id',id);toast(error?error.message:'Estado actualizado');if(!error){closeModal();loadSection()}}
async function toggleGeoStatus(table,id,current){const col=table==='cities'||table==='zones'?'status':'is_active';const value=col==='status'?(current?'disabled':'active'):(current?false:true);const {error}=await sb.from(table).update({[col]:value}).eq('id',id);if(error)return toast(error.message);toast('Estado actualizado');loadSection()}
async function geography(c){const [p,ci,z]=await Promise.all([fetchRows('provinces',['name','is_active','created_at']),fetchRows('cities',['name','province_id','status']),fetchRows('zones',['name','city_id','status'])]);c.innerHTML=pageHead('Geografía','Argentina → provincia → ciudad → zona','<button class="primary" onclick="openGeoCreate()">+ Nueva</button>')+`<div class="geo-grid">${[['Provincias',p],['Ciudades',ci],['Zonas',z]].map(([t,rows])=>`<article class="panel"><div class="panel-head"><h3>${t}</h3><span>${rows.length}</span></div><div class="compact-list">${rows.slice(0,40).map(r=>`<div class="compact-row"><span>${esc(r.name)}</span><button class="pill-btn ${statusClass(r.status??(r.is_active?'active':'inactive'))}" onclick="toggleGeoStatus('${t==='Provincias'?'provinces':t==='Ciudades'?'cities':'zones'}','${r.id}',${r.is_active===false?'false':(r.status==='disabled'?'false':'true')})">${esc(r.status??(r.is_active?'active':'inactive'))}</button></div>`).join('')||'<p class="muted">Sin registros.</p>'}</div></article>`).join('')}</div>`}
async function catalog(c){const [cats,skills]=await Promise.all([fetchRows('categories',['name','is_active','sort_order']),fetchRows('skills',['name','category_id','is_active'])]);c.innerHTML=pageHead('Categorías y skills','Catálogo que alimenta los perfiles y la búsqueda.','<button class="primary" onclick="openCatalogCreate()">+ Nuevo</button>')+`<div class="two-panels"><article class="panel"><div class="panel-head"><h3>Categorías</h3><span>${cats.length}</span></div>${cats.map(r=>`<div class="compact-row"><span>${esc(r.name)}</span><span class="pill ${statusClass(r.is_active?'active':'inactive')}">${r.is_active?'active':'inactive'}</span></div>`).join('')||'<p class="muted">Sin registros.</p>'}</article><article class="panel"><div class="panel-head"><h3>Skills</h3><span>${skills.length}</span></div>${skills.map(r=>`<div class="compact-row"><span>${esc(r.name)}</span><span class="pill ${statusClass(r.is_active?'active':'inactive')}">${r.is_active?'active':'inactive'}</span></div>`).join('')||'<p class="muted">Sin registros.</p>'}</article></div>`}
async function settings(c){const {data,error}=await sb.from('system_settings').select('key,value,description,updated_at').order('key');c.innerHTML=pageHead('Configuración','Parámetros generales de DISPONIBLE');if(error){c.innerHTML+=`<div class="empty-card">${esc(error.message)}</div>`;return}c.innerHTML+=`<div class="settings-grid">${(data||[]).map(r=>{const val=typeof r.value==='object'?JSON.stringify(r.value):String(r.value??'');return `<article class="setting-card"><span>${esc(r.key)}</span><b>${esc(val)}</b>${r.description?`<small>${esc(r.description)}</small>`:''}<button class="small-btn" onclick="openSettingEditor(${JSON.stringify(r.key)},${JSON.stringify(val)},${JSON.stringify(r.description||'')})">Editar</button></article>`}).join('')||'<div class="empty-card">Todavía no hay configuraciones cargadas.</div>'}</div>`} 
function openSettingEditor(key,value,description){openModal(`<div class="modal-head"><div><span class="eyebrow">CONFIGURACIÓN</span><h2>Editar parámetro</h2></div><button class="close" onclick="closeModal()">×</button></div><label>Clave<input value="${esc(key)}" disabled></label><label>Valor JSON<textarea id="setting-value" rows="8" spellcheck="false">${esc(value)}</textarea></label><label>Descripción<input id="setting-description" maxlength="300" value="${esc(description)}"></label><p class="muted">El valor debe ser JSON válido. No se permite cambiar la clave.</p><button class="primary full" onclick="saveSetting(${JSON.stringify(key)})">Guardar cambios</button>`)}
async function saveSetting(key){const raw=document.querySelector('#setting-value')?.value.trim();const description=document.querySelector('#setting-description')?.value.trim()||null;if(!raw)return toast('Ingresá un valor.');let value;try{value=JSON.parse(raw)}catch(e){return toast('El valor no es JSON válido.')}const {error}=await sb.from('system_settings').update({value,description,updated_at:new Date().toISOString()}).eq('key',key);if(error)return toast(error.message);toast('Configuración actualizada');closeModal();loadSection()}
async function openGeoCreate(){
  const [provinces,cities]=await Promise.all([fetchRows('provinces',['name','is_active']),fetchRows('cities',['name','province_id','status'])]);
  openModal(`<div class="modal-head"><div><span class="eyebrow">GEOGRAFÍA</span><h2>Nueva ubicación</h2></div><button class="close" onclick="closeModal()">×</button></div>
  <label>Tipo<select id="geo-type" onchange="refreshGeoParentFields()"><option value="provinces">Provincia</option><option value="cities">Ciudad</option><option value="zones">Zona</option></select></label>
  <div id="geo-parent-fields"></div><label>Nombre<input id="geo-name" maxlength="120" required placeholder="Nombre"></label>
  <button class="primary full" onclick="createGeoRecord()">Crear ubicación</button>`);
  window._geoParents={provinces,cities}; refreshGeoParentFields();
}
function refreshGeoParentFields(){const type=document.querySelector('#geo-type')?.value,box=document.querySelector('#geo-parent-fields');if(!box)return;if(type==='provinces')return box.innerHTML='';if(type==='cities')return box.innerHTML=`<label>Provincia<select id="geo-parent">${(window._geoParents?.provinces||[]).map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select></label>`;box.innerHTML=`<label>Ciudad<select id="geo-parent">${(window._geoParents?.cities||[]).map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select></label>`}
async function createGeoRecord(){const type=document.querySelector('#geo-type')?.value,name=document.querySelector('#geo-name')?.value.trim(),parent=document.querySelector('#geo-parent')?.value;if(!name)return toast('Ingresá un nombre.');const slug=slugify(name);const payload={name,slug};if(type==='provinces')Object.assign(payload,{country_code:'AR',is_active:true});if(type==='cities')Object.assign(payload,{province_id:parent,status:'coming_soon'});if(type==='zones')Object.assign(payload,{city_id:parent,status:'coming_soon'});const {error}=await sb.from(type).insert(payload);if(error)return toast(error.message);toast('Ubicación creada');closeModal();loadSection()}
async function openCatalogCreate(){const cats=await fetchRows('categories',['name','is_active','sort_order']);openModal(`<div class="modal-head"><div><span class="eyebrow">CATÁLOGO</span><h2>Nuevo elemento</h2></div><button class="close" onclick="closeModal()">×</button></div><label>Tipo<select id="cat-type" onchange="refreshCatalogFields()"><option value="categories">Categoría</option><option value="skills">Skill</option></select></label><div id="catalog-fields"></div><button class="primary full" onclick="createCatalogRecord()">Crear elemento</button>`);window._catalogParents={cats};refreshCatalogFields()}
function slugify(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,120)}
function refreshCatalogFields(){const type=document.querySelector('#cat-type')?.value,box=document.querySelector('#catalog-fields');if(!box)return;if(type==='categories')return box.innerHTML='<label>Nombre<input id="cat-name" maxlength="120" placeholder="Nombre de categoría"></label><label>Orden<input id="cat-order" type="number" min="0" value="0"></label>';box.innerHTML=`<label>Nombre<input id="cat-name" maxlength="120" placeholder="Nombre de skill"></label><label>Categoría<select id="cat-parent"><option value="">Sin categoría</option>${(window._catalogParents?.cats||[]).map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select></label>`}
async function createCatalogRecord(){const type=document.querySelector('#cat-type')?.value,name=document.querySelector('#cat-name')?.value.trim();if(!name)return toast('Ingresá un nombre.');let payload={name,slug:slugify(name),is_active:true};if(type==='categories')payload.sort_order=Number(document.querySelector('#cat-order')?.value||0);else{const parent=document.querySelector('#cat-parent')?.value;if(parent)payload.category_id=parent}const {error}=await sb.from(type).insert(payload);if(error)return toast(error.message);toast('Elemento creado');closeModal();loadSection()}
function openModal(html){let m=document.querySelector('#admin-modal');if(!m){m=document.createElement('div');m.id='admin-modal';m.className='modal-backdrop';document.body.append(m)}m.innerHTML=`<div class="modal">${html}</div>`;m.classList.add('show')}
function closeModal(){document.querySelector('#admin-modal')?.classList.remove('show')}
async function login(){const {error}=await sb.auth.signInWithPassword({email:document.querySelector('#email').value,password:document.querySelector('#pass').value});if(error)return toast(error.message);session=(await sb.auth.getSession()).data.session;render()}
async function logout(){await sb.auth.signOut();session=null;render()}
init();
